[global]
developmentMode = false
showWarningOnDirectExecution = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[theme]
primaryColor = "#1f4e79"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"